### ISSUE TITLE
More details about data availability in ELIXIR?

### ISSUE THREAD

**Issue by dhimmel** [bartg01/NestedFCV.SNF#1]
Greetings, I came to this repo via the following study:

**Integrative Analysis Reveals a Molecular Stratification of Systemic Autoimmune Diseases**   
Guillermo Barturen, Sepideh Babaei, Francesc Català‐Moll, Manuel Martínez‐Bueno, Zuzanna Makowska, Jordi Martorell‐Marugán, Pedro Carmona‐Sáez, Daniel Toro‐Domínguez, Elena Carnero‐Montoro, María Teruel, … Marta E. Alarcón‐Riquelme  
*Arthritis & Rheumatology* (2020-12-08) <https://doi.org/gjksz3>   
DOI: [10.1002/art.41610](https://doi.org/10.1002/art.41610) · PMID: [33497037](https://www.ncbi.nlm.nih.gov/pubmed/33497037)

The paper includes:

> #### Data and code availability
> Data is available upon request in ELIXIR in agreement with privacy rules of the European Union. Gene expression and DNA methylation data can be explored at http://bioinfo.genyo.es/precisesadsdata/. The R code used for clustering is available at: https://github.com/bartg01/NestedFCV.SNF

Thanks for posting the R code and the expression/methylation webapp.

Is there a direct link to the dataset page in ELIXIR? Or some sort of accession number. Haven't used ELIXIR before, but when I got to https://elixir-europe.org/, not quite sure how to proceed with any sort of data request?

**Comment by bartg01** [comment]
Dear Daniel

Please contact with the sustainability committee of PRECISESADS in order to get further instructions to access the dataset (https://r3lab.uni.lu/frozen/th9v-xt85).

Best

**Comment by dhimmel** [comment]
Thanks @bartg01 for the link. Cool to see that the data request page has a DOI: https://doi.org/10.17881/th9v-xt85.
